=== avans-night-byte/engine/Resources/XML/Schemas/resources.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:cmn="Common"
        xmlns:comp="Components"
        xmlns:res="GameResources"
        targetNamespace="GameResources">

    <xs:import schemaLocation="common.xsd"
               namespace="Common"/>
    <xs:import schemaLocation="components.xsd"
               namespace="Components"/>

    <xs:complexType name="baseGameResource">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="path" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="resources">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="basePath" type="xs:string"/>
                <!-- Textures -->
                <xs:element name="textures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="texture" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource"/>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Sprites -->
                <xs:element name="sprites">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sprite" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource">
                                            <xs:sequence>
                                                <xs:choice>
                                                    <xs:element name="definition" type="xs:string"/>
                                                    <xs:element ref="cmn:size"/>
                                                </xs:choice>
                                            </xs:sequence>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Sounds -->
                <xs:element name="sounds">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sound" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource"/>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Music -->
                <xs:element name="music">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="music" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource"/>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Scenes -->
                <xs:element name="scenes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="scene" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource"/>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- Levels -->
                <xs:element name="levels">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="level" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource">
                                            <xs:sequence>
                                                <xs:element name="spriteName" type="xs:string"/>
                                                <xs:element name="spriteSheetPath" type="xs:string"/>
                                                <xs:element name="tmxPath" type="xs:string"/>
                                            </xs:sequence>
                                        </xs:extension>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <!-- PreObjects -->
                <xs:element name="objectLists">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="objectList" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:complexContent>
                                        <xs:extension base="res:baseGameResource"/>
                                    </xs:complexContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== avans-night-byte/engine/Resources/XML/Definition/Resources.xml
<?xml version="1.1" encoding="UTF-8"?>
<gr:resources
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="GameResources  ../Schemas/resources.xsd"
        xmlns:common="Common"
        xmlns:gr="GameResources">
    <basePath>../../Resources/</basePath>
    <textures>
        <texture>
            <name>mainmenu_background</name>
            <path>Sprites/background.png</path>
        </texture>
    </textures>
    <sprites>
        <sprite>
            <name>character</name>
            <path>Sprites/character.png</path>
            <common:size>
                <width>1</width>
                <height>1</height>
            </common:size>
        </sprite>
    </sprites>
    <sounds>
        <sound>
            <name>oof</name>
            <path>Sounds/oof.wav</path>
        </sound>
    </sounds>
    <music>
        <music>
            <name>background_mainmenu</name>
            <path>Sounds/background.wav</path>
        </music>
    </music>
    <scenes/>
    <levels/>
</gr:resources>


        <!--
            <textures>
                <texture>
                    <name>photo_martijn</name>
                    <path>../../Resources/....</path>
                </texture>
            </textures>
            <sprites>
                <sprite>
                    <name>character</name>
                    <path>../images//...</path>
                    <jsonPath>../../Resources/sprite.json</jsonPath>
                </sprite>
                <sprite>
                    <name>bruh</name>
                    <path>../../images/</path>
                    <size>
                        <width>16</width>
                        <height>16</height>
                    </size>
                </sprite>
            </sprites>
            <sounds>

            </sounds>
            <music>

            </music>
            <scenes>

            </scenes>
            <levels>
                <level>
                    <name>level_1</name>
                    <path>/Resources/example.tmx</path>
                </level>
                <level>
                    <name>gunshop</name>
                    <path>/Resources/gunshop.tmx</path>
                </level>
            </levels>
        -->
